@url = http://localhost:8081

### POST add Blog post
POST {{url}}/api/blog

{
    "title": "My First Blog Post 5",
    "content": "This is my Second blog post. It's not very long, but it's a start.",
    "author": "John Dong",
    "created_at": "2021-01-02"
}

### Get Blog List
GET {{url}}/api/blog
Accept: application/json

### Get Blog Post
GET {{url}}/api/blog/1
Accept: application/json

### Delete Blog Post
DELETE {{url}}/api/blog/1
Accept: application/json