### Get Furniture List
GET http://localhost:8081/api/furniture
Accept: application/json

### POST Add to Furniture List
POST http://localhost:8081/api/furniture
Accept: application/json

{
    "name": "Modern Chair",
    "description": "A sleek modern chair.",
    "price": 199.99,
    "image_url": "https://example.com/chair.jpg",
    "category": "Chairs",
    "colors": ["red", "blue", "green"],
    "sizes": ["small", "medium", "large"],
    "images": ["https://example.com/img1.jpg", "https://example.com/img2.jpg"]
}

### DELETE Furniture Item
DELETE http://localhost:8081/api/furniture/1
Accept: application/json

### POST add Blog post
POST http://localhost:8081/api/blog

{
    "title": "My First Blog Post 5",
    "content": "This is my Second blog post. It's not very long, but it's a start.",
    "author": "John Dong",
    "created_at": "2021-01-02"
}

### Get Blog List
GET http://localhost:8081/api/blog
Accept: application/json

### Get Blog Post
GET http://localhost:8081/api/blog/1
Accept: application/json

### Delete Blog Post
DELETE http://localhost:8081/api/blog/1
Accept: application/json

### Get Hello
GET http://localhost:8081/hello
