### Get Furniture List
GET http://localhost:8081/api/furniture
Accept: application/json

### POST Furniture List
POST http://localhost:8081/api/furniture
Accept: application/json

{
    "name": "Modern Chair",
    "description": "A sleek modern chair.",
    "price": 199.99,
    "image_url": "https://example.com/chair.jpg",
    "category": "Chairs",
    "colors": ["red", "blue", "green"],
    "sizes": ["small", "medium", "large"],
    "images": ["https://example.com/img1.jpg", "https://example.com/img2.jpg"]
}

### Get Hello
GET http://localhost:8081/hello
