@url = http://localhost:8081

### Create user
POST {{url}}/api/users
Content-Type: application/json

{
    "username": "john doe1",
    "password": "password1",
    "email": "test1@mail.ru"
}

### Update user
PUT {{url}}/api/users/3
Content-Type: application/json

{
    "username": "john doe2",
    "password": "password2",
    "email": ""
}